### ISSUE TITLE
[To Do] Error Fixing

### ISSUE THREAD

**Issue by bbm3h14aku** [nikkimas/ProBank#13]
in File tty.c at 78 function scanfTTY
Error conflicting Types for scanfTTY

**Comment by nikkimas** [comment]
Failed Code:

char scanfTTY()
{
    char inp;
    scanf("%s", &inp);
    fflush(stdin);
    return inp;
 }

**Comment by bbm3h14aku** [comment]
change return type to

const char \* scanfTTY()
{
const char \* inp;
scanf("%s", inp);
fflush(stdin);
return inp;
}
